import { clientsClaim } from 'workbox-core';
import { precacheAndRoute } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { NetworkOnly } from 'workbox-strategies';

clientsClaim();
self.skipWaiting();

// Precache all the assets generated by the build process.
precacheAndRoute(self.__WB_MANIFEST || []);

// Handle Socket.io requests with NetworkOnly strategy
registerRoute(
  ({ url }) => url.pathname.startsWith('/socket.io/'),
  new NetworkOnly({
    cacheName: 'socket-io',
    networkTimeoutSeconds: 10,
  }),
);
